import Head from "next/head"
import { useEffect, useRef, useState } from "react"
import Form from "../components/Form"
import Table from "../components/Table"
import { checkMatching, getRandomInt } from "../utils"

type Guess = { guess: string; matchingLetterCount: number }
type FormDataType = { guess: string }

export default function Home() {
  const answer = useRef<string>("")
  const [data, setData] = useState<Guess[]>([])
  const [isMatched, setIsMatched] = useState(false)

  useEffect(() => {
    const randomQuestion = ["book", "javascript", "reactjs"]

    answer.current = randomQuestion[getRandomInt(0, randomQuestion.length)]

    setIsMatched(false)
  }, [isMatched])

  const reset = () => setData([])

  const onSubmit = ({ guess }: FormDataType) => {
    if (!guess) return

    const matchingInfo = checkMatching(guess, answer.current)

    if (matchingInfo.isFullMatch) {
      setIsMatched(true)
      alert(`Congratulations! The answer is ${answer.current}`)
      reset()
      return
    }

    setData((prev) => [
      ...prev,
      { guess, matchingLetterCount: matchingInfo.count },
    ])
  }

  return (
    <div className="p-4">
      <Head>
        <title>Guess Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-4xl">Guess The Word!</h1>
      <Form<FormDataType> onSubmit={onSubmit} />
      <Table<Guess>
        headers={[
          { title: "Guess", align: "left" },
          { title: "Matching Letters", align: "left" },
        ]}
        data={data}
      />
    </div>
  )
}
